### ISSUE TITLE
Kitty terminal is broken 

### ISSUE THREAD

**Issue by rdgh8** [pop-os/beta#312] opened 2021-11-27 07:33 UTC
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Fresh install in a VM
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Kitty 0.23.1 (newest version)

**Issue/Bug Description:**

On Pop!_OS 21.10 beta, opening Kitty with the Pop Shell enabled will not work correctly. It looks like the kitty window is stretched from the top of the screen to the bottom, despite the presence of the system panel at the top, resulting in overlap. 

**Steps to reproduce (if you know):**

1. Install Kitty ([binary install](https://sw.kovidgoyal.net/kitty/binary/))
2. Launch Kitty 

Sometimes the issue is present, sometimes Kitty works fine. 

**Expected behavior:**

Kitty launches normally, as it does on 21.04

**Other Notes:**

Here is a demo, I open and close Kitty multiple times and you can see that it is stretched out usually, but also sometimes works correctly. 
https://user-images.githubusercontent.com/66289396/143672592-6410f56b-bc44-493c-8add-f513dd10e753.mp4

**Comment by leviport** [comment] 2021-11-29 16:35
Thanks for helping test the beta! This issue sounds like a duplicate of https://github.com/pop-os/shell/issues/1232.

**Closed by leviport** 2021-11-29 16:35 UTC
