### ISSUE TITLE
[21.04] Launcher not returning all the items from Applications List (custom .desktop files)

### ISSUE THREAD

**Issue by x2ws** [pop-os/beta#183] opened 2021-06-19 05:30 UTC
Props to the development team. Can't wait for the final release.

**How did you upgrade to 21.04? (Fresh install / Upgrade)**
Fresh Install

**Issue/Bug Description:**
Installed Joplin via the official AppImage install script, which downloads the AppImage and creates a .desktop file. The application is listed in the Application list and I can start Joplin from applications but unfortunately not able to search for it via the launcher. Same issue with downloading the Bitwarden image and setting up a .desktop file in .local/share/applications folder. After multiple online searches, I decided to reinstall PopOS completely again (thinking I did something that screwed this up), performed all the updates from PopShop then before installing anything else, attempted to install Joplin and still same issue with launcher.

**Steps to reproduce (if you know):**
Create a custom .desktop file. The application list will pick it up and you can run it. Launch the Launcher and perform a search for the application. Launcher will not locate it.

**Expected behavior:**
Ability to search and start any applications that are listed in the Applications list

**Other Notes:**
Probably does not matter, but I have a Dell XPS 15 9500 (10th gen i7, 16GB RAM, and 512GB SSD). This worked before, not sure why it stopped working, possibly one of the new updates caused this issue.

**Comment by x2ws** [comment] 2021-06-19 16:12
Just installed Postman, which is not an AppImage and had to create a postman.desktop file. Same issue, shows up in Applications list, also able to search for it in the Applications screen but nothing is returned when I search for it in the Launcher.

**Comment by jacobgkau** [comment] 2021-06-21 14:26
Thank you for the report. This was caused by https://github.com/pop-os/shell/pull/1005 (removal of hard-coded search directories from the launcher) and is fixed by https://github.com/pop-os/default-settings/pull/114 (addition of ~/.local/share to XDG_DATA_DIRS).

**Comment by jacobgkau** [comment] 2021-06-21 20:22
Fixed by https://github.com/pop-os/shell/pull/1018. (The default-settings PR was taking the wrong approach.)

**Closed by jacobgkau** 2021-06-21 20:22 UTC
