### ISSUE TITLE
Dock briefly reappears after unlock

### ISSUE THREAD

**Issue by SUPERCILEX** [pop-os/beta#156] opened 2021-06-04 23:24 UTC
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

Upgraded from 20.10.

**Issue/Bug Description:**

With the dock disabled, the dock briefly reappears after unlocking. So suspend -> wakeup -> unlock -> dock is there and then hides itself.

**Comment by leviport** [comment] 2021-06-07 14:31
Duplicate of https://github.com/pop-os/cosmic/issues/41

**Closed by leviport** 2021-06-07 14:31 UTC
