### ISSUE TITLE
New Xorg update to 21.1 from Ubuntu appears to conflict with Nvidia drivers

### ISSUE THREAD

**Issue by quinzee33** [pop-os/beta#362] opened 2022-04-02 11:48 UTC
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

 
Fresh install
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
xserver-xorg-core:
  Installed: 2:1.20.14-1ubuntu1
  Candidate: 2:21.1.3-2ubuntu2
  Version table:
     2:21.1.3-2ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
 *** 2:1.20.14-1ubuntu1 100
        100 /var/lib/dpkg/status
```

(Along with the many other Xorg components)

```
nvidia-driver-510:
  Installed: 510.54-1pop0~1645719405~22.04~10b5fec
xserver-xorg-video-nvidia-510:
  Installed: 510.54-1pop0~1645719405~22.04~10b5fec
```

**Issue/Bug Description:**

Trying to update the system through the Pop Shop presents an error that:

```
The following packages have unmet dependencies:
xserver-xorg-video-nvidia-510:Depends:
xorg-video-abi-24 or
xorg-video-abi-23 but it is not installable 
xorg-video-abi-20 but it is not installable 
xorg-video-abi-19 but it is not installable 
xorg-video-abi-18 but it is not installable 
xorg-video-abi-15 but it is not installable 
xorg-video-abi-14 but it is not installable 
xorg-video-abi-13 but it is not installable 
xorg-video-abi-12 but it is not installable 
xorg-video-abi-11 but it is not installable 
xorg-video-abi-10 but it is not installable 
xorg-video-abi-8 but it is not installable 
xorg-video-abi-6.0 but it is not installable
```
It does not allow me to continue with the installation.

Looking at the output for the equivalent of an `apt full-upgrade` using [nala](https://gitlab.com/volian/nala) for better formatting:

![nala_upgrade_autoremove](https://user-images.githubusercontent.com/101351551/161381354-a18c0752-bb26-4aef-9fd3-b37944a3b075.png)

All of these nvidia packages will be removed if I proceed with the upgrade from the terminal.

A regular `apt upgrade` shows:
```
The following packages have been kept back:
  xserver-xorg-core xserver-xorg-video-amdgpu xserver-xorg-video-ati
  xserver-xorg-video-fbdev xserver-xorg-video-intel xserver-xorg-video-nouveau
  xserver-xorg-video-qxl xserver-xorg-video-radeon xserver-xorg-video-vesa
  xserver-xorg-video-vmware
```

**Steps to reproduce (if you know):**

Attempt to upgrade from the terminal or Pop Shop while using the Nvidia 510 drivers

**Expected behavior:**

The xorg upgrade to succeed while still keeping the Nvidia drivers.

**Other Notes:**

I will perform a normal apt upgrade from the terminal with xorg being held back. Hopefully this can be resolved as Xorg 21.1 would be a [particularly good update](https://www.phoronix.com/scan.php?page=news_item&px=X.Org-AsyncFlipSecondaries) for my mixed monitor setup and one that I've been waiting on for quite some time.

**Comment by RayJW** [comment] 2022-04-05 11:42
I can confirm this is still happening on multiple devices. Does someone know how to fix this issue though? I wasn't as smart and expected a new driver to be installed afterwards.

**Comment by KitsuneAlex** [comment] 2022-04-05 16:11
Okay, starting from a fresh install, this seems to be the best workaround for now:
```sh
sudo apt update 
&& sudo apt upgrade 
&& sudo apt purge nvidia-* 
&& sudo apt autoremove
```
Reboot.
```
sudo apt install nvidia-driver-510
```
Reboot again, everything should work fine and all packages should be up-to-date.

**Comment by jackpot51** [comment] 2022-04-05 16:14
Fixed with the latest NVIDIA driver

**Closed by jackpot51** 2022-04-05 16:14 UTC

**Comment by falk-stefan** [comment] 2024-04-11 22:19
Getting the same on Ubuntu 22.04 with NVIDIA 545.29.06

```none
$ sudo apt-get install cuda-11-6
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-video-nvidia-510 : Depends: xorg-video-abi-24 but it is not installable or
                                          xorg-video-abi-23 but it is not installable or
                                          xorg-video-abi-20 but it is not installable or
                                          xorg-video-abi-19 but it is not installable or
                                          xorg-video-abi-18 but it is not installable or
                                          xorg-video-abi-15 but it is not installable or
                                          xorg-video-abi-14 but it is not installable or
                                          xorg-video-abi-13 but it is not installable or
                                          xorg-video-abi-12 but it is not installable or
                                          xorg-video-abi-11 but it is not installable or
                                          xorg-video-abi-10 but it is not installable or
                                          xorg-video-abi-8 but it is not installable or
                                          xorg-video-abi-6.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by ahmedetefy** [comment] 2024-05-21 19:15
^ +1 Also running into similar issues

**Comment by jacobgkau** [comment] 2024-05-22 01:16
@ahmedetefy This is the Pop!_OS beta repository. Pop!_OS 22.04 was released from beta over two years ago.

Are you running Pop!_OS 22.04? Do you have any pre-release staging branches added? What is the exact issue you're having (exact error message and/or terminal output)? The general Pop!_OS repository for when you don't know where to file an issue is https://github.com/pop-os/pop.

**Comment by jacobgkau** [comment] 2024-05-22 01:18
@falk-stefan It looks like you're attempting to install a CUDA package, so that sounds different from Xorg attempting to remove the NVIDIA driver itself as this issue was talking about.

Are you running Pop!_OS or Ubuntu? If it's Ubuntu, is this with the System76 PPA added on System76 hardware?
