### ISSUE TITLE
CS:GO not launching, I can't seem to find what does it and searched everything.

### ISSUE THREAD

**Issue by EysseW** [pop-os/beta#305] opened 2021-11-17 16:28 UTC
Hi there, not sure if it is a fault of the beta release, but my cs:go is not working on 21.10. I tried everything. It is remarkable to see it worked fine on 21.04 and I asked it on reddit where 2 people said they had the same issue since 21.10. I think it has something to do with the beta release. What it is, I am not sure of.
I upgrade to 21.10, not fresh install.

This issue was also reported on ValveSoftware/csgo-osx-linux#2815, but with other 21.10 distros. However, this fix doesn't seem to work on the pop beta...

**Comment by leviport** [comment] 2021-11-17 16:30
Why was https://github.com/pop-os/beta/issues/248 closed and this issue opened?

**Comment by leviport** [comment] 2021-11-17 16:34
Duplicate of https://github.com/pop-os/beta/issues/248

There's no need to open multiple issues, just update the issue that already exists.

**Closed by leviport** 2021-11-17 16:34 UTC
