### ISSUE TITLE
Automatic Search on typing in overview / workspaces view gone

### ISSUE THREAD

**Issue by jmbuhr** [pop-os/beta#169] opened 2021-06-09 08:33 UTC
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

Upgrade from 20.10 

**Issue/Bug Description:**
Previously, the old  "activities overview" would show workspaces and seamlessly switch to searching apps, settings and files once the user started typing. This one-stop-shop felt very intuitive for a keyboard-centric workflow and, especially when it comes to files, it finds them with more ease than the new launcher. The latest update removed the feature to automatically start searching when typing in the workspaces view, I assume in an attempt to further separate workspaces and applications.

**Steps to reproduce (if you know):**
Open workspaces view and start typing

**Expected behavior:**
I would  love for pop-os to retain the automatic switching to the search on typing in the overview / workspaces view.

**Comment by jacobgkau** [comment] 2021-06-09 13:43
Thank you for trying the beta. This is intended behavior; see https://github.com/pop-os/cosmic/issues/66.

Type-to-search still works in the Applications view as well as the Pop Shell launcher. The Pop Shell launcher would be the new "one-stop-shop" for opening and switching applications. The launcher also has a file browser, accessible by typing `~` to start in the home directory, `/` to start in the root directory, or `d:` to display recently-opened files. Feedback about making the launcher more useful is welcome at https://github.com/pop-os/shell/issues.

I'm closing this issue for now since this change was made intentionally, but we appreciate the feedback and will keep it in mind.

Related: https://github.com/pop-os/cosmic/issues/18

**Closed by jacobgkau** 2021-06-09 13:43 UTC
