### ISSUE TITLE
Applications view empty

### ISSUE THREAD

**Issue by genebean** [pop-os/beta#251] opened 2021-10-20 02:29 UTC
While using the live image, I clicked Applications from both the top menu and the dock and, in both instances, nothing was there - it was like no apps were installed, including the ones obviously there and available from the dock.

**Comment by leviport** [comment] 2021-10-20 15:50
Thanks for helping test the beta! I believe this bug is a duplicate of https://github.com/pop-os/pop/issues/1894

**Closed as completed by leviport** 2021-10-20 15:50 UTC
