### ISSUE TITLE
Tile Window Plugin: Keyboard layout must be able to be changed

### ISSUE THREAD

**Issue by srueegger** [pop-os/beta#57] opened 2020-04-21 18:34 UTC
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Fresh Install

**Issue/Bug Description:**
Sorry for my bad English.

With a Swiss (German) keyboard layout, the shortcut for the application starter "Super + /" is impossible to activate. So it would be good if you could adjust the shortcuts.

**Steps to reproduce (if you know):**
use the Tiling Plugin with a Swiss (German) Keyboard Layout

**Comment by leviport** [comment] 2020-04-21 19:08
Thanks for the report! We did add these shortcuts to the Keyboard Shortcuts section of gnome-control-center, so they can be modified from there. You can find the launcher hotkey entry under "Navigate Applications and Windows".
![2020-04-21_13-06](https://user-images.githubusercontent.com/13512097/79903808-f714e780-83d0-11ea-9f78-4bfb0af90ee3.png)

**Comment by WatchMkr** [comment] 2020-04-21 22:30
We'll be working to fix this as well. Duplicate of https://github.com/pop-os/shell/issues/196

**Closed by WatchMkr** 2020-04-21 22:30 UTC
