### ISSUE TITLE
22.04: Wallpaper switching behavior seems off

### ISSUE THREAD

**Issue by Sadin** [pop-os/beta#230] opened 2021-10-14 20:15 UTC
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Fresh install 21.10 + Nvidia Drivers
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

GNOME, GNOME Shell

**Issue/Bug Description:**

Wallpaper doesn't switch on actual desktop when selected in GNOME, but switches in workspace view.
Don't believe this is strictly upstream as I have GNOME40 + Fedora 34 running on my Thinkpad.

Examples: https://imgur.com/a/0CBDfjd

![alt text](https://i.imgur.com/mMblCyK.jpg)
![alt text](https://i.imgur.com/3wyvK2Y.png)

**Steps to reproduce (if you know):**

Attempt to swap wallpapers

**Expected behavior:**

Wallpaper should swap when selected.

**Other Notes:**

Have rebooted, this is post fresh install, no changes has been made no packages added.
Did not test if this happened in live preview from flash drive.

**Comment by ryanrms** [comment] 2021-11-12 16:07
I can confirm this issue, I'm running a Ratel Performance (2013) but with AMD graphics card (RX 570). I upgraded from  21.04 using pop-upgrade, and my first guess was that the wallpaper functionality provided by the custom Pop! "Desktop settings" is disconnected from dconf. 

But this is not the case, running "gsettings set org.gnome.desktop.background picture-uri "file:///home/user/Pictures/Wallpaper/example.png"
Ends up changing the desktop wallpaper shown in the Pop! Desktop settings window, instead of actually changing the wallpaper.  

Other thing I tried was disabling all the (GNOME) extensions one by one, even with them all turned off I still couldn't get the wallpaper to change.

I ran gnome-control-center in verbose mode in terminal but the only message when changing backgrounds was:

`(gnome-control-center:19105): dconf-DEBUG: 09:05:31.397: change_fast`

`(gnome-control-center:19105): dconf-DEBUG: 09:05:31.397: change_notify: /org/gnome/desktop/background/`

`(gnome-control-center:19105): dconf-DEBUG: 09:05:31.398: change_fast`

`(gnome-control-center:19105): dconf-DEBUG: 09:05:31.398: change_notify: /org/gnome/desktop/screensaver/`

**Comment by ryanrms** [comment] 2021-11-14 07:16
I can't sleep but may have found something that helps determine where the bug is, as well as a workaround!

The issue is definitely with the extension "Desktop Icons NG (DING)", I have successfully got the wallpaper to change to the correct one (from the default) by disabling this extension in the Extensions program, and then restarting GNOME Shell (alt+F2, type "r" and hit enter).  

Hopefully this helps in fixing it.

**Comment by inffy** [comment] 2021-11-16 14:21
If you update the extensioon throug extensions.gnome.org it seems to fix this behaviour

**Comment by jackpot51** [comment] 2021-11-18 16:29
I will pull updates from DING into our packaged version

**Comment by jackpot51** [comment] 2021-11-18 17:07
Pushed to https://github.com/pop-os/desktop-icons-ng/tree/master

**Comment by jackpot51** [comment] 2021-11-22 15:07
I am not seeing this anymore after updating DING

**Comment by leviport** [comment] 2022-03-29 22:05
Looks like this is back in Jammy

**Comment by XV-02** [comment] 2022-03-29 22:13
The failure the change seems to persist across gnome-shell and gdm restarts, a full system reboot, and even a shutdown and boot.

**Comment by lukeofthetauri** [comment] 2022-03-31 15:18
I'd like to note that it seems this only affects dark theme- I am able to change the background when I amusing light mode, but going back to dark keeps the wallpaper set from light-theme.

**Comment by jackpot51** [comment] 2022-03-31 18:29
Should be fixed in https://github.com/pop-os/gnome-shell/pull/95 and https://github.com/pop-os/desktop/pull/83

**Closed** 2022-04-01 22:19 UTC
Labels: 22.04
