### ISSUE TITLE
Asus F512 laptop AMD background unable to change while in dark mode

### ISSUE THREAD

**Issue by Yellowfoam** [pop-os/beta#356] opened 2022-04-01 20:26 UTC
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 upgraded from 21.10

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

background wallpaper

**Issue/Bug Description:**
Desktop background will not change while in dark mode.
Switch to light mode background will change and will stay changed when switching back to dark mode.

**Steps to reproduce (if you know):**
happens everytime

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment] 2022-04-01 22:21
Thank you for testing the beta! This sounds like a duplicate of https://github.com/pop-os/beta/issues/230 (which was reopened for this bug in 22.04). This was recently fixed and released, so system updates should fix it.

**Closed by leviport** 2022-04-01 22:21 UTC
