### ISSUE TITLE
Application Overview does not show any applications when a second monitor is attached

### ISSUE THREAD

**Issue by nathanbibb** [pop-os/beta#240] opened 2021-10-17 15:17 UTC
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

Fresh Install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
When clicking the "Show Applications" icon on the dock, I see all application icons.  However, if I plug in a second monitor (tested using USB-C and HDMI on a Lemur Pro lemp9), the "Show Applications" overview shows a blank gray screen with no applications shown.  Behavior persists after monitor is unplugged, until session is restarted by logging out or restarting the computer.  Searching for applications still works.

**Steps to reproduce (if you know):**
1. Plug in second monitor to Lemur Pro running Pop_OS! 21.10
2. Click "Show Applications" icon on the dock

**Expected behavior:**
Application overview is shown with all installed application icons.

**Other Notes:**

**Comment by Kartonrealista** [comment] 2021-10-18 11:02
I've noticed the same issue. Temporary fix - restart the gnome shell (press Alt+F2, type in r and press Enter).

**Comment by leviport** [comment] 2021-10-18 17:37
Duplicate of https://github.com/pop-os/pop/issues/1894

**Closed by leviport** 2021-10-18 17:37 UTC
