### ISSUE TITLE
Super + left click drag does not drag windows 

### ISSUE THREAD

**Issue by rdgh8** [pop-os/beta#321] opened 2021-12-01 18:43 UTC
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Fresh install in VM
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

N/A

**Issue/Bug Description:**

In 21.04, you can press the super key and left click on any location on a window to drag the window around. This is really useful because I have titlebars turned off to save space, and this allows me to still manually drag a window around. 

**Steps to reproduce (if you know):**

Super + left click drag

**Expected behavior:**

Window drags around screen following cursor 

**Other Notes:**

I'm not sure if this is a bug or if it was purposely removed, but it's a really useful feature so I hope it doesn't go away.

**Comment by leviport** [comment] 2021-12-01 18:53
It's still working for me, both on my Oryx with 21.10 and in a 21.10 VM I just spun up in Gnome Boxes. What are you using to virtualize?

**Comment by rdgh8** [comment] 2021-12-01 18:55
I'm using KVM + virtmanager

**Comment by jabbermacy** [comment] 2021-12-01 18:59
works here, gnome default

**Comment by rdgh8** [comment] 2021-12-01 19:03
Only unique thing I can think of that I'm doing is that I have left alt and left win swapped in tweaks (keyboard -> additional layouts -> alt/win key behaviour)?

**Comment by jacobgkau** [comment] 2021-12-01 19:12
> Only unique thing I can think of that I'm doing is that I have left alt and left win swapped in tweaks (keyboard -> additional layouts -> alt/win key behaviour)?

I can recreate Left Super + Left Click no longer dragging a window after activating that option; however, with the option activated, Left Alt + Left Click does drag the window. This seems like expected behavior to me. Does holding Alt instead of Super work for you, since you have those swapped via that option?

**Comment by rdgh8** [comment] 2021-12-01 19:21
I am unable to test as my super key is broken so I have to have it swapped with left alt to access window controls. Is there any way to revert back to 21.04 behavior? In 21.04 with the keys swapped, left super + left click works fine.

**Comment by leviport** [comment] 2021-12-01 19:43
>Is there any way to revert back to 21.04 behavior?
It hasn't changed. Did you also make the swap in the VM as well? Layout changes like that don't always get passed through to the VM. For example, if I set my host machine's keyboard layout to Dvorak, then make a VM with the keyboard layout set to QWERTY, the VM's input language will be QWERTY, not Dvorak.

**Comment by jacobgkau** [comment] 2021-12-01 19:49
> my super key is broken so I have to have it swapped with left alt to access window controls.

> In 21.04 with the keys swapped, left super + left click works fine.

I want to clarify, you mean your physical Left Alt key (which is acting as Left Super) + Left Click works fine, right? (I don't understand how else it could work fine if it's physically broken.)

**Comment by rdgh8** [comment] 2021-12-01 20:04
My physical super key is broken, so in Gnome Tweaks on both 21.04 host and 21.10 VM I have swapped left alt and left super so that my physical left alt acts as super in Gnome. On both 21.04 and 21.10, this simulated super key works perfectly for everything, except only on 21.10 it doesn't work for this one specific thing (dragging windows). 

After having these two keys swapped in software, I do not know if physical left super (now simulated left alt) would work to drag windows as I cannot activate this key. I just want to be clear, this issue is only present on 21.10. I have both 21.04 host and 21.10 VM configured identically, but window dragging only does not work on 21.10.

**Comment by leviport** [comment] 2022-06-03 15:32
I've been using several laptops with LAlt and Super flipped from gnome-tweaks, and it's been working just fine for me. I'm going to close this for now.

**Closed by leviport** 2022-06-03 15:32 UTC
