### ISSUE TITLE
The dock comes out vertically

### ISSUE THREAD

**Issue by ianhundere** [pop-os/beta#227] opened 2021-10-14 12:19 UTC
How did you upgrade to 21.10? (Fresh install / Upgrade)

`sudo pop-upgrade release upgrade -f`
from 21.04

Issue/Bug Description:
the dock shows up vertically instead of horizontally

Steps to reproduce (if you know):
not sure how to reproduce. i got it to stop by turning off the cosmic dock extension and then turning it back on again.

Expected behavior:
the dock shouldn't pop up like some sorta space odyssey monolith.

**Comment by goldyfruit** [comment] 2021-11-03 12:52
The issue seems to have disappeared.

**Comment by krulkrul** [comment] 2021-11-23 16:34
I have the same behavior, it started around a week ago. Before it was okay. I have been shuffling with the dock settings (intelligence hide, extending to edges of screen, custom size etc) but this does not help. Restarting gnome always makes it disappear, sometimes after waking up i see it and it disappears within a second but most of times it stays vertically.

**Comment by leviport** [comment] 2021-11-23 16:37
Dang, I thought this bug went away. Anything in particular that makes it happen consistently?

**Comment by krulkrul** [comment] 2021-11-23 20:50
i might found a clue...it could be caused by gnome extension 'Vertical overview'. I completely disabled that extension and so far so good. There is a configuration setting in that extension that gave me a hint ('Enable dash overrides, disable if you use another entension that replaces the dash')

Wonder if user @goldyfruit and @ianhundere had same extension installed at times of the problems.

**Comment by leviport** [comment] 2021-11-23 20:57
Vertical Overview should have been replaced by Cosmic Workspaces, although that update did require a `sudo apt full-upgrade` to install properly. Can you send the output of `sudo apt list --upgradable` to see if a package called `pop-session` needs an update? If that upgrade has been kept back on your system, that could explain why everyone else saw the issue disappear with updates.

**Comment by goldyfruit** [comment] 2021-11-23 23:42
I don't have `Vertical Overview` extension anymore.

**Comment by krulkrul** [comment] 2021-11-24 05:46
I do see indeed a new version for pop-session:

```sudo apt list --upgradable
Listing... Done
bluez-cups/impish-security,impish-updates 5.60-0ubuntu2.1 amd64 [upgradable from: 5.60-0ubuntu2]
bluez-obexd/impish-security,impish-updates 5.60-0ubuntu2.1 amd64 [upgradable from: 5.60-0ubuntu2]
bluez/impish-security,impish-updates 5.60-0ubuntu2.1 amd64 [upgradable from: 5.60-0ubuntu2]
gnome-shell-extension-desktop-icons-ng/impish,impish 20-1pop0~1637682135~21.10~2a407ca all [upgradable from: 20-1pop0~1631240010~21.10~9b107f6]
libbluetooth3/impish-security,impish-updates 5.60-0ubuntu2.1 amd64 [upgradable from: 5.60-0ubuntu2]
pop-session/impish,impish 5.0.0~1635367371~21.10~52ccc11 all [upgradable from: 5.0.0~1632324886~21.10~0e196e0]
pop-shop/impish 3.4.2pop0~1637689735~21.10~69242e0 amd64 [upgradable from: 3.4.2pop0~1637170608~21.10~642c5c9]
slack-desktop/jessie 4.22.0 amd64 [upgradable from: 4.19.2]```
I will do a 'apt full-upgrade'

**Comment by krulkrul** [comment] 2021-11-25 18:35
You can close this issue...the 'apt full-upgrade' resolved the conflicts with the different extensions (also some other workspace related issues i had :) )

**Comment by leviport** [comment] 2021-11-29 16:04
Glad to hear it, thanks for the update!

**Closed by leviport** 2021-11-29 16:04 UTC
