### ISSUE TITLE
Unable to navigate Workspace with Cosmic Workspaces disabled

### ISSUE THREAD

**Issue by Crylia** [pop-os/beta#279] opened 2021-11-05 20:54 UTC
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
upgrade
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Cosmic Workspace V6

**Issue/Bug Description:**
When disabling the Cosmic Workspaces and returning to gnome 40 default behaviours you are unable to switch workspaces with <SUPER> + <STRG> + <UP> / <DOWN>
This gets pretty frustrating because I personally dont want to use the old Gnome workspaces anymore.

**Steps to reproduce (if you know):**
Disable Cosmic Workspaces and try to switch workspaces with your keyboard

**Expected behavior:**
Beeing able to switch workspaces like in default Gnome 40

**Other Notes:**
Maybe I'm blind, but I seems like that the default keybindings for gnome 40 are missing? The only workspace related one I found said "Moving workspace UP/Down" which makes sense for vertical, but not horizontal workspaces.

**Comment by jacobgkau** [comment] 2021-11-08 16:52
Thank you for trying the beta! This sounds like a duplicate of https://github.com/pop-os/beta/issues/226, so I'm closing this issue as a duplicate. If I'm mistaken, please let us know the difference and this can be re-opened.

**Closed by jacobgkau** 2021-11-08 16:52 UTC
