### ISSUE TITLE
Black screen on boot after passing disc encryption prompt

### ISSUE THREAD

**Issue by peterHoburg** [pop-os/beta#388] opened 2022-04-12 02:46 UTC
**How did you upgrade to 22.04? (Fresh install / Upgrade)**
Upgrade from 21.10

**Issue/Bug Description:**
Black screen on boot post disc encryption prompt. The only solution I have found is to keep turning the computer on/off until it finally boots correctly. This can be anywhere from 1 to 10 times.
A terminal is available by pressing super-F2.

**Steps to reproduce (if you know):**
* Shutdown computer
* Turn on
* Enter encryption password
* Screen is black

**Expected behavior:**
Enter Gnome in a single boot.

**Other Notes:**
Kudu6 running in NVIDIA graphics mode. I have some logs if needed.

This is highly reproducible for me. It happens every time I shut down the laptop.

**Comment by markmaas** [comment] 2022-04-12 12:48
Same thing here. Framework laptop so iris XE graphics. I can alt-f2 and login.

Bluetooth works, I have wireless connected, I can reach the internet, etc. But no login prompt.

**Comment by markmaas** [comment] 2022-04-12 15:18
I've been able to figure out its GDM3 that does not want to start. Somehow it hangs.

**Comment by leviport** [comment] 2022-04-12 16:10
Is the OS fully up-to-date? I thought this one was fixed already.

**Comment by xploz1on** [comment] 2022-04-12 17:56
## It is exactly the same issue i have. Fresh install fully upgraded.
Reported [https://github.com/pop-os/beta/issues/386](url)
I made some alias in my .zshrc. ALT F2, and do a:
`sudo systemctl restart gdm.service`
No need to start it again.
The logs point to something faulty with

**Comment by leviport** [comment] 2022-04-12 20:07
You're right @xploz1on , I'll close this one as a duplicate of https://github.com/pop-os/beta/issues/386

**Closed by leviport** 2022-04-12 20:07 UTC
