### ISSUE TITLE
Pop!_OS 22.04 doesn't install on VMware when using Legacy

### ISSUE THREAD

**Issue by Cikappa2904** [pop-os/beta#366] opened 2022-04-03 14:53 UTC
### **How did you upgrade to 22.04? (Fresh install / Upgrade)**
Fresh install on VM
 

### **Issue/Bug Description:**
The installation fails when installing Pop!_OS 22.04 on VMware with Legacy BIOS, works when using UEFI.
I do not encrypt the drive when installing.

- **Host OS**: Windows 11 x64 

- **VMware Version**: Workstation Pro 16.2.2
- **VM**: Pop!_OS 22.04 with default settings for Ubuntu x64

![vmware_dNIzCfR97l](https://user-images.githubusercontent.com/49496033/161433667-34790a36-e9e2-4dec-b2ae-193ed4dc63c5.png)

[installer.log](https://github.com/pop-os/beta/files/8404769/installer.log)

### **Steps to reproduce (if you know):**
Create a VM with the default settings for Ubuntu x64, try to install Pop!_OS 22.04

### **Expected behavior:**
For it to correctly install

**Comment by leviport** [comment] 2022-04-07 17:34
Thanks for testing the beta! I think this might be the same issue as https://github.com/pop-os/beta/issues/364

**Comment by manyet1k** [comment] 2022-04-12 18:05
Not really, because that issue (which I opened) 1) occurs on QEMU and not VMware, and 2) doesn't result in a "Could Not Install" but rather it prevents the VM from booting.

Unfortunately, I don't have any clue about fixing this issue.

**Comment by n3m0-22** [comment] 2022-04-22 17:09
I can't reproduce this. Are you using the Intel/AMD or NVIDIA iso? Also have you tried this again with the newest beta? This one worked for me. [pop-os_22.04_amd64_intel_3.iso](https://pop-iso.sfo2.cdn.digitaloceanspaces.com/22.04/amd64/intel/3/pop-os_22.04_amd64_intel_3.iso)

**Comment by leviport** [comment] 2022-04-22 17:13
I believe this was fixed with https://github.com/pop-os/distinst/pull/289

**Closed** 2022-04-22 17:13 UTC
