### ISSUE TITLE
Sleeping the laptop crashes and requires a hard reboot.

### ISSUE THREAD

**Issue by nexes** [pop-os/beta#280] opened 2021-11-06 19:02 UTC
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 Fresh install:  NVIDIA ISO build 2 on 11-06-2021

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

N/A

**Issue/Bug Description:**
When putting the laptop to sleep, the green indicator never turns white (sleep may not be happening), when opening the lid the screen remains black and is unresponsive to input. Requires a hard reset.

**Steps to reproduce (if you know):**
1. Close the laptop lid.
2. wait a few seconds
3. Open the lid

**Expected behavior:**
The system wakes and is usable

**Other Notes:**
Laptop: Razer Blade 15 (mid 2021). Intel i7-11800H; Nvidia GeForce RTX 3070 Max-Q; 32GB memory
Kernel: 5.15.0-76051500-generic
Nvidia driver: 470.82.00
Nvidia profile: Nvidia Graphics and Hybrid Graphics (both have the problem)
OS: Pop!_OS 21.10 Beta

dmesg output after I logged back in from the crash.
[dmesg-sleep.txt](https://github.com/pop-os/beta/files/7491090/dmesg-sleep.txt)

**Comment by jacobgkau** [comment] 2021-11-08 16:24
Thank you for trying the beta. This issue should possibly be merged with https://github.com/pop-os/beta/issues/274, which is for a Razer Blade Stealth 13.

**Comment by jabbermacy** [comment] 2021-11-09 21:18
^ probably right, I heard about suspend concerns, zero issues here, Predator Triton 500 SE (i11+3060), something specific to razor hardware??

**Comment by jacobgkau** [comment] 2021-11-09 21:58
I've renamed https://github.com/pop-os/beta/issues/274 to be a bit more general and am closing this one as a duplicate of https://github.com/pop-os/beta/issues/274. If there's reason to believe the issues are separate, just let us know and this can be re-opened.

**Closed by jacobgkau** 2021-11-09 21:58 UTC
