### ISSUE TITLE
Kernel 5.15.5 makes Intel 6th Gen CPUs failing to poweroff/suspend, slow to boot/reboot + iGPU issues.

### ISSUE THREAD

**Issue by spxak1** [pop-os/beta#340] opened 2021-12-13 18:27 UTC
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
Fresh install of beta 3.
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Kernel 5.15.5

**Issue/Bug Description:**
Intel Sandy Bridge (6th Gen) CPUs will not reboot, poweroff or suspend when VT-d is enabled.

More here:  https://github.com/pop-os/linux/issues/86

iGPU also produces artefacts.
More here: https://github.com/pop-os/linux/issues/89

**Steps to reproduce (if you know):**
Install Beta 3, boot (takes a long time), poweroff (never shuts down).

**Expected behavior:**
Boots fast, powers off, resumes from sleep.

**Other Notes:**
This is the issue reported here: https://github.com/pop-os/linux/issues/86

While with beta 2 we could revert back to 5.15.0 after the 5.15.5 upgrade, with beta 3, there is no old kernel to fall back to. 
If the release version of 21.10 uses 5.15.5 all Sandy Bridge users are going to be in trouble. 

Please either don't use 5.15.5 (5.15.0 is fine) or delay 21.10 until this (and others, like write through issue ([here](https://github.com/pop-os/linux/issues/87)) are fixed.

Thank you.

**Comment by leviport** [comment] 2021-12-13 19:40
Duplicate of https://github.com/pop-os/linux/issues/86

**Closed by leviport** 2021-12-13 19:40 UTC
