### ISSUE TITLE
Application Menu is too big in 1366x768

### ISSUE THREAD

**Issue by ghost** [pop-os/beta#393] opened 2022-04-13 14:41 UTC
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

 

Fresh Install

**Issue/Bug Description:**

Application menu is too big in 1366x768 (16:9) display, it takes up a large part of the screen.
![Screenshot from 2022-04-12 10-27-22](https://user-images.githubusercontent.com/72671699/163205772-67eb44da-f413-4f9d-b047-b916be224bdb.png)

**Comment by leviport** [comment] 2022-04-13 15:27
Duplicate of https://github.com/pop-os/cosmic/issues/314, but thank you for helping test the beta!

**Closed as completed by leviport** 2022-04-13 15:27 UTC
