### ISSUE TITLE
Pop!_Shop unmet dep error when updating

### ISSUE THREAD

**Issue by veronicacary** [pop-os/beta#196] opened 2021-06-29 15:41 UTC
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

> From Pop!_OS 20.10.

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

> gnome-shell-extension-cosmic-dock
> gnome-shell-extension-ubuntu-dock

**Issue/Bug Description:**
I'm getting an error when running Pop!_Shop on the beta this morning. Here's the error message:

```
The following packages have unmet dependencies:
  gnome-shell-extension-cosmic-dock: Breaks: gnome-shell-extension-ubuntu-dock but 69ubuntu1pop0~1624393749~21.04~00aed10 is to be installed
```

**Steps to reproduce (if you know):**
Perform update as per typical Pop!_Shop behavior.

**Expected behavior:**
For the update to function without breaking dependencies.

**Other Notes:**
This is on a Galp4, if that's helpful. Let me know if you need anything else!

**Comment by leviport** [comment] 2021-06-29 15:43
Duplicate of https://github.com/pop-os/beta/issues/194

**Closed by leviport** 2021-06-29 15:43 UTC
