### ISSUE TITLE
Workspaces 

### ISSUE THREAD

**Issue by aman220320072007** [pop-os/beta#168] opened 2021-06-09 03:00 UTC
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

I upgraded from Pop os 20.10
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

When I press superkey+d it creates an unescapable window there is no workspaces in left and when you click the window it doesn't 
take us to the windo

**Steps to reproduce (if you know):**
superkey+d

**Expected behavior:**

there should be a workspace window in the left side which doesn't exist 

**Other Notes:**

**Comment by aman220320072007** [comment] 2021-06-09 03:01
This happens only sometimes not always

**Comment by jacobgkau** [comment] 2021-06-09 13:33
Duplicate of #144.

This has been fixed, the update has just not been released from proposed yet.

**Closed by jacobgkau** 2021-06-09 13:33 UTC
