### ISSUE TITLE
Pop!_Shop hangs when searching right after application start

### ISSUE THREAD

**Issue by ololizoz** [pop-os/beta#331] opened 2021-12-07 23:17 UTC
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
Fresh install
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop!_Shop
```
pop-shop:
  Installed: 3.4.2pop0~1637689735~21.10~69242e0
  Candidate: 3.4.2pop0~1637689735~21.10~69242e0
  Version table:
 *** 3.4.2pop0~1637689735~21.10~69242e0 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
If you start to write in the search bar right after starting Pop!_Shop, the application freezes and has to be force killed and restarted. If you wait a few seconds before starting to write in the search box, the issue doesn't occur.

**Steps to reproduce (if you know):**
Open Pop!_Shop. Immediately start to write in search box.

**Expected behavior:**
Hang/crash.

**Comment by ololizoz** [comment] 2021-12-07 23:19
On second thought, maybe this issue should be reported in pop-os/shop? Please let me know if that's the case.

**Comment by ggobbe** [comment] 2021-12-10 08:04
Cannot reproduce both when it is the first sync of sources (fresh install) and with sources already synced before.

**Comment by xploz1on** [comment] 2022-04-14 02:13
This happens because every time you open Pop Shop! it tries to look for updates and makes it freeze sometimes until it finishes.
So this depends on your internet speed. Mines is really slow and happens almost every time.

**Comment by n3m0-22** [comment] 2022-04-22 14:34
Many improvements have been made to pop-shop recently. I can't reproduce this issue. It may take a moment for Pop!_Picks and Recently Updated to load based on your connection speed but the app itself is not freezing. I'm closing this issues, but I can always reopen if you are still having the problem.

**Closed by n3m0-22** 2022-04-22 14:34 UTC

**Comment by xploz1on** [comment] 2022-04-22 22:07
> Many improvements have been made to pop-shop recently. I can't reproduce this issue.The app itself is not freezing even while Pop!_Picks and Recently Updated are loading. I'm closing this issues, but I can always reopen if you are still having the problem.

True. I have not seen this happens anymore. It even queues installs as its refreshing the repos.
