### ISSUE TITLE
Firefox won't work without title bars

### ISSUE THREAD

**Issue by daleosm** [pop-os/beta#2] opened 2020-04-06 23:58 UTC
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 Upgrade

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Firefox 74.0.1 (64-bit)

**Issue/Bug Description:**

I used to save screen space by using Firefox without title bars. It now when enabled creates a double tittle bar.

**Steps to reproduce (if you know):**

 Setting in customization menu

**Expected behavior:**

**Other Notes:**

**Comment by rhb388** [comment] 2020-04-07 01:50
I'm having this same issue.

**Comment by danielecappuccio** [comment] 2020-04-07 15:49
Same here.

**Comment by evil-arri** [comment] 2020-04-17 17:14
Fresh 20.04 install. I can confirm the same issue.

**Comment by jeroen7s** [comment] 2020-04-18 08:04
Same issue here, seems to be Pop specific.
This is super anoying
when running using the terminal firefox says `Failed to load module "appmenu-gtk-module"`
when trying to install it `sudo apt install appmenu-gtk-module` it does autocomplete the package name, but when trying to install it says that it can't find it -_-

**Comment by algnc** [comment] 2020-04-18 11:49
Same issue. Workaround: Disable the pop-shell extension, or disable title bars in the extension (which will remove title bars for other applications)

**Comment by under810** [comment] 2020-04-22 19:36
Having same issue on fresh install. Only thing that works is using an extension to hide title bar but that hides it for all apps.

**Comment by matrix8967** [comment] 2020-04-24 14:58
I posted a work around in https://github.com/pop-os/beta/issues/61

But I'm reposting here:

`sudo apt install appmenu-gtk2-module appmenu-gtk3-module`

Then launch Firefox from a terminal with: `GTK_CSD=1 firefox`

I'm assuming you can edit firefox's desktop file, but I'm gonna wait to figure out the root cause before I do that.

**Comment by jdgarcia1381** [comment] 2020-04-25 18:25
Same problem here. It's working but cannot remove the title bar:
![image](https://user-images.githubusercontent.com/13160502/80287628-23de3d00-86f8-11ea-82c5-a8bec11695a9.png)
I did a clean 20.04 install.

**Comment by jakobhellermann** [comment] 2020-04-25 21:47
Running Firefox with `env GTK_CSD=0` works for me

**Comment by raulcraveiro** [comment] 2020-04-27 20:32
Same here. :/

**Comment by jackpot51** [comment] 2020-04-27 20:40
What's the output of `apt-cache policy pop-shell` ?

The installed version should be `0.1.0~1587966468~20.04~5866554`

**Comment by algnc** [comment] 2020-04-27 20:42
> What's the output of `apt-cache policy pop-shell` ?
> 
> The installed version should be `0.1.0~1587966468~20.04~5866554` (as of when I made this comment)

I saw there was an updated so I tried it again, and still had the same issue.

pop-shell:
  Installed: 0.1.0~1587966468~20.04~5866554
  Candidate: 0.1.0~1587966468~20.04~5866554
  Version table:
 *** 0.1.0~1587966468~20.04~5866554 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Comment by isantop** [comment] 2020-04-27 20:47
I'm seeing this issue on that version here.

```
# apt policy pop-shell
pop-shell:
  Installed: 0.1.0~1587966468~20.04~5866554
  Candidate: 0.1.0~1587966468~20.04~5866554
  Version table:
 *** 0.1.0~1587966468~20.04~5866554 1002
       1002 http://apt.pop-os.org/staging/master focal/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master focal/main i386 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by matrix8967** [comment] 2020-04-27 20:58
Issue persists for me on version `0.1.0~1587966468~20.04~5866554` of pop-shell.

Here is a list of other enabled extensions for reference. 

``` 
['batteryiconfix@kylecorry31.github.io', 'pop-shop-details@system76.com', 'pop-suspend-button@system76.com', 'system76-power@system76.com', 'noannoyance@sindex.com', 'audio-switcher@AndresCidoncha', 'dash-to-dock@micxgx.gmail.com', 'donotdisturb@kylecorry31.github.io', 'TopIcons@phocean.net', 'remove-dropdown-arrows@mpdeimos.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'clipboard-indicator@tudmotu.com', 'pop-shell@system76.com', 'hidetopbar@mathieu.bidon.ca', 'screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com', 'arc-menu@linxgem33.com']
```

**Comment by jackpot51** [comment] 2020-04-27 21:09
I was able to reproduce with `Title Bar` turned off in the Firefox Customize menu, and title bars turned on in pop-shell.

**Comment by matrix8967** [comment] 2020-04-27 21:21
@jackpot51 Would a quick-and-dirty fix for now be to just duplicate the `Title Bar` button into the `Pop-Shell` options icon/menu? I actually had no idea that was an option until I opened up Tweaks and looked in those options instead.

**Comment by matrix8967** [comment] 2020-04-27 23:10
A quick and jank work around is to copy or edit the desktop files for Firefox and Thunderbird that live in: `/usr/share/applications/firefox.desktop` and /usr/share/applications/thunderbird.desktop`

Replacing the `Exec=` lines with the following:

`Exec=env GTK2_RC_FILES=/usr/share/themes/Pop-dark/gtk-2.0/gtkrc GTK_THEME=Pop-dark:dark GTK_CSD=1 /usr/bin/firefox %u`

for each respective line. 

Obviously don't go mucking around in your `*.desktop` files unless you understand the `.desktop` file standard, but this will keep me from having to launch firefox / thunderbird in a `guake` terminal for now. 

Light bathroom reading for desktop file standard: https://developer.gnome.org/integration-guide/stable/desktop-files.html.en

**Comment by mmstick** [comment] 2020-04-29 15:46
Issue fixed a few days ago

**Comment by algnc** [comment] 2020-04-29 16:06
Just updated and upgraded all packages and still have this issue.

**Comment by CKH4** [comment] 2020-05-02 07:20
I believe this is still an issue for non-english systems due to localization changing the window title (which is used to determine whether to force the titlebar). I haven't reproduced the issue myself, but from the subreddit:

![picture of firefox with double title bars. the window title is "Navegador web Firefox"](https://i.redd.it/yx7qyw6w07w41.png)

https://reddit.com/r/pop_os/comments/gbn3i3/problems_in_pop_os_2004_with_firefox_since_the/
https://reddit.com/r/pop_os/comments/gbi6ry/disabling_titlebar_in_firefox_doesnt_work_in_pop/

**Comment by jackpot51** [comment] 2020-05-02 12:24
We could probably use wm_class instead

**Comment by brs17** [comment] 2020-05-15 19:07
This should have been resolved with https://github.com/pop-os/shell/commit/11f6f10112134d4983d7df4f7047155db3544f5c

**Closed by brs17** 2020-05-15 19:07 UTC
