### ISSUE TITLE
[21.04] Iso exits from GUI after boot when Ethernet is plugged in

### ISSUE THREAD

**Issue by Cantello** [pop-os/beta#153] opened 2021-06-04 19:05 UTC
**How did you upgrade to 21.04? (Fresh install / Upgrade)**
Fresh install.
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
When booting from a USB drive (created with Etcher, ventoy & dd directly) the installation starts normally, the GUI appears, I can choose language (chose English & American English) and then the install goes back to text mode and 5 tasks are running, `casper-md5check` among others (I also remembered the CUPS daemon) which never terminate (waited for half an hour).

**Steps to reproduce (if you know):**
Boot from the created USB drive.

**Expected behavior:**
Installation continues normally.

**Other Notes:**
This is on a desktop PC (Ryzen 5600X, B550 motherboard, Nvidia 3070 graphics card).

**Comment by bflanagin** [comment] 2021-06-04 20:52
Thanks for the report @Cantello. Was this the nvidia iso or the intel iso?

**Comment by Cantello** [comment] 2021-06-04 21:53
> Thanks for the report @Cantello. Was this the nvidia iso or the intel iso?

Sorry for the omission, it was the nvidia ISO.

**Comment by Cantello** [comment] 2021-06-06 10:51
Upgrading from 20.10 works, btw. No hassles or errors at all.

**Comment by bflanagin** [comment] 2021-06-07 18:49
I'm not seeing this issue on my end (used ventoy and popsicle) . I'd suggest downloading the image again and seeing if a fresh download fixes the issue.

**Comment by ebbit1q** [comment] 2021-06-22 19:00
I'm having the same issue, after a few seconds of showing the install screen it shuts down gnome again.
gtx 1080 + ryzen 1700X, I'm using efi and have disabled secure boot, I prepared the usb stick with popsicle.
here is the syslog from the writable section of the usb: https://gist.github.com/ebbit1q/576066f04a627a4051a3c4a2878c7e21
the line at :3241 and its surroundings seem related to the issue: `gnome-shell: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.`

**Comment by AndreasSturm** [comment] 2021-06-27 07:00
Had the same issue, unplugging the network cable until the OS has fully loaded solved the problem, after OS has fully loaded I plugged the network cable in and I was able to install 21.04 withou any issues.

**Comment by ebbit1q** [comment] 2021-06-27 11:28
I found something related to network in the log but thought it was a red herring

I've installed 21.04 as well now:
- I've double checked my system was using efi
- after booting from the usb and having the shell crash I've opened a tty with ctrl shift f3
- logging in with the usb stick has the username pop-os without password
- after that I simply restarted the desktop manager with `sudo systemctl start gdm`
- then I could continue using the usb stick and install without issue

**Comment by ebbit1q** [comment] 2021-06-27 12:09
this line specifically in the log seemed related to network issues https://gist.github.com/ebbit1q/576066f04a627a4051a3c4a2878c7e21#file-syslog-L1917 `nm-dispatcher[1705]: /etc/network/if-up.d/resolved: 12: mystatedir: not found`, I'll test later if I can boot from the usb stick without network.

**Comment by jacobgkau** [comment] 2021-06-28 16:47
We were able to recreate this on an oryp4 last week, instructions to recreate are here: https://github.com/pop-os/iso/issues/279#issue-930443436

**Comment by bflanagin** [comment] 2021-06-30 19:49
I've been able to reproduce the issue on most of our machines in the lab. (galp5, lemp9[using usb ethernet adapter], Thelio-r1, gazelle15)

The issue only occurs when using a usb flash drive in conjunction with having the ethernet cable plugged in. Not all flash drives or usb storage devices cause the issue.
 
These logs are from one of the machines that is failing.

[dmesg.txt](https://github.com/pop-os/beta/files/6743587/dmesg.txt)
[journalctl.txt](https://github.com/pop-os/beta/files/6743588/journalctl.txt)

**Comment by LincolnAuster** [comment] 2021-07-01 01:20
I observed this on my machine (Ryzen 3900X, RTX 2060) with the 21.04 release Nvidia ISO as well - unplugging ethernet made everything work, and the issue was only in the live environment, not in the installed system.

As it seems to be dependent on the USB drive, `lsusb` reports that mine is a `058f:6387 Alcor Micro Corp. Flash Drive`

**Comment by leviport** [comment] 2021-07-07 15:48
The latest published versions of the 21.04 isos include a fix for this issue.

**Closed by leviport** 2021-07-07 15:48 UTC
