### ISSUE TITLE
Disabling Cosmic Workspaces Extension Breaks Shell Theme

### ISSUE THREAD

**Issue by funnylookinhat** [pop-os/beta#293] opened 2021-11-12 15:50 UTC
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
Fresh install
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Cosmic Workspaces Extension

**Issue/Bug Description:**
Disabling the Cosmic Workspaces extension seems to break some of the theming of the top bar in gnome.

Notice the color change in the top bar.

**Disabled - Notice theme is correct in top bar**

![disabled](https://user-images.githubusercontent.com/397918/141494856-c42470da-a37f-48e9-955b-e07c131eec43.png)

**Enabled - Theme changes for top bar**

![enabled](https://user-images.githubusercontent.com/397918/141494873-1ecba078-ed7f-42a1-8ff1-66bc82ac4da4.png)

**Steps to reproduce (if you know):**

Open Extension -> Toggle COSMIC Workspaces Off

**Expected behavior:**

Top bar color would not change.

**Other Notes:**

I know this seems minor, but I figured it may be breaking the theme elsewhere and you may want to know.

**Comment by jacobgkau** [comment] 2021-11-12 16:11
Duplicate of https://github.com/pop-os/beta/issues/278.

**Closed by jacobgkau** 2021-11-12 16:11 UTC
