### ISSUE TITLE
Shotwell Flatpak-version crashes whole system

### ISSUE THREAD

**Issue by pHamala** [pop-os/beta#314] opened 2021-11-29 18:16 UTC
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
org,gnome.shotwell 0.30.14

**Issue/Bug Description:**
Launching Shotwell crashes the whole system. Screen freezes and system is unresponsive. Only option is to hard reboot.

**Steps to reproduce (if you know):**

    

1. Installed Pop Os Beta 21.10.
2. Sync files from Nextcloud to Nextcloud folder on /home
3. Install Shotwell (flatpak) from Pop Shop
4. Open Shotwell and set photo library to /home/Nextcloud/Pictures (65 GB of photos and videos). Check mark to watch library over new content.
5. Shotwell starts to search photos/videos
6. After couple of seconds the whole system freezes. Only option is to hard reboot.

    

**Expected behavior:**
App should work without system crash

**Other Notes:**
[journalctl_log.txt](https://github.com/pop-os/beta/files/7620335/journalctl_log.txt)

[syslog.txt](https://github.com/pop-os/beta/files/7635586/syslog.txt)

**Comment by pHamala** [comment] 2021-11-29 18:21
[error_log.txt](https://github.com/pop-os/beta/files/7620329/journalctl_log.txt)

**Comment by pHamala** [comment] 2021-11-29 18:22
[journalctl_log.txt](https://github.com/pop-os/beta/files/7620333/journalctl_log.txt)

**Comment by jacobgkau** [comment] 2021-11-29 18:28
Thank you for trying the beta. I am not seeing this issue on a lab machine with an Intel CPU and NVIDIA graphics. What hardware are you using? When the freeze occurs, does Ctrl-Alt-F5 work to get you to a full-screen terminal?

**Comment by pHamala** [comment] 2021-11-29 18:38
No I can't. The system is completely unresponsive. Only option is to hard reboot with power button. I'm using a system with AMD Ryzen 4500U with integrated graphics.

**Comment by pHamala** [comment] 2021-11-29 18:44
[syslog.txt](https://github.com/pop-os/beta/files/7620426/syslog.txt)

Launched app in mark 20:38:44

**Comment by pHamala** [comment] 2021-12-01 17:03
Same thing happened now with gThumb. Installed it from Pop Store and tried to open a photo from /home/Nextcloud/Photos/pic.jpg. Couple of seconds later whole system freezes. Not sure if connected to problem in Shotwell but it is awfully similar.

[journalctl.txt](https://github.com/pop-os/beta/files/7635800/journalctl.txt)

**Comment by pHamala** [comment] 2021-12-02 14:33
I'm on with Wayland but it happens also with xorg.

**Comment by pHamala** [comment] 2021-12-03 15:22
It seems that this problem is somewhat connected to kernel. I installed Kernel 5.15.6 from Ubuntu Mainline and now apps work as they should without system crash. The one is crashing is the latest kernel update on 21.10.

**Comment by jacobgkau** [comment] 2021-12-03 19:05
If the problem is fixed by kernel 5.15.6, then https://github.com/pop-os/linux/pull/85 should fix it.

**Comment by pHamala** [comment] 2021-12-23 13:25
Problem seems to be solved with latest Kernel release 5.15.8

**Closed** 2021-12-23 15:25 UTC
