### ISSUE TITLE
[Bug] The application overview is completely broken

### ISSUE THREAD

**Issue by Kartonrealista** [pop-os/beta#243] opened 2021-10-18 11:27 UTC
**How did you upgrade to 21.10? (Upgrade)**
Upgraded from Pop!_OS 21.04
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Applications overview

**Issue/Bug Description:**

Numerous issues, ranging from graphical bugs (this + overlapping icons)
![Zrzut ekranu z 2021-10-18 13-17-53](https://user-images.githubusercontent.com/63356574/137721141-15aa1f00-121a-4537-b8d1-3224a6f52c87.png)
to problems with folder creation or placing things into existing folders.
Duplicated icons within and outside of folders (here musicbrainz picard). It's not just graphical either, it actually is duplicated and clickable.
![Zrzut ekranu z 2021-10-18 13-24-57](https://user-images.githubusercontent.com/63356574/137721756-90bcd561-66d2-452f-a2ad-edd65ea44912.png)

**Comment by x2ws** [comment] 2021-10-19 03:08
I am having the same issue on a Dell XPS 15 9500. Performed an upgrade following instructions. No themes or 3rd party extensions installed. It is not random for me. It is not displaying any applications at all, even after restart.

**Comment by Kartonrealista** [comment] 2021-10-19 05:23
@juanejot @x2ws you're experiencing https://github.com/pop-os/pop/issues/1894. On the other hand, that solution didn't work for me permanently.

**Comment by juanejot** [comment] 2021-10-19 09:40
> @juanejot @x2ws you're experiencing [pop-os/pop#1894](https://github.com/pop-os/pop/issues/1894). On the other hand, that solution didn't work for me permanently. A better temporary solution is to just restart the gnome shell. You have to do this every restart until they fix that issue

Thanks you for the insight, and yes it presents as a similar problem, but:
A) Being posted in the pop-is/pop repo, that issue, also listed by their comments about version, is about hirsute (21.04, I assume final), not impish (the 21.10 beta we’re testing). Though it’s a good thought, as other issues I’ve seen on the other machine indeed carried over from 21.04 to 21.10.
B) I’ve never installed Dash-to-Dock or any other non-Pop!_OS GNOME extensions to this installation (in fact, I have the Firefox extension that otherwise would be able to access them for install, turned off). I acknowledge that perhaps retaining the Firefox extension at all might carry over settings of completely separate (even non-Pop!_OS) installations, and therefore may have some bearing; happy to test when next I’m in front of the computer, likely tomorrow; and
C) The workaround of typing in an app name into “Search Applications…” is not a successful one for me with this installation; I tried it in fact when I first noticed this behavior, and while app icons that might match your search come up directly under that search bar, along with various menu headings from Settings, etc. you might mean, neither during that search, nor after.
The only “solution” for now is simply to leave the system running for some time scale on the order of hours, and check back on it, upon which time it seems to be able to populate app icons when invoked.
Total speculation makes me wonder whether that UI component/library (whichever it is) has very slow access under 21.10 beta currently, to an icon cache it needs; potentially a cache to which other interface items (including the search bar) have quicker access?

**Comment by Kartonrealista** [comment] 2021-10-19 09:50
@juanejot The cosmic dock is just a modified dash to dock. That's the same reason why Pop shop process shows up in the system monitor as elementary appcenter. There's no need to reinvent the wheel in a FOSS project.

**Comment by juanejot** [comment] 2021-10-19 22:40
Thank you indeed. Testing to completely remove the GNOME Additions extension from Firefox (which, only on a non-Pop!_OS system, I've ever used to install Dash-to-Dock) & then reboot resulted in the same behavior as above, including after updating via command line to (Pop!_Shop interestingly made no mention of the availability of) generic kernel 5.31.0-20 and the gnome-shell-extension-cosmic-workspaces of today.

Thank you too, @mmstick, for the info on the upcoming updates to the application overview. Looks like it's all coming together well!

**Comment by jabbermacy** [comment] 2021-11-08 18:23
turn off/on cosmic dock fixes issue 100% of the time

**Comment by juanejot** [comment] 2021-11-08 19:59
@jabbermacy I concur that seems to work. Dunno whether COSMIC or any of its particular extensions being loaded at boot/login is the kind of thing that can be re-enabled by `systemctl enable`, but yours is a good workaround until a new Application Picker closer to final. Thanks!

**Comment by jabbermacy** [comment] 2021-11-08 22:27
ALSO, this bug does not exist on Wayland, only X11, 100% confirmed, 3 times

**Comment by juanejot** [comment] 2021-11-08 23:56
The latest update of the following packages seems to have removed this issue, my only personal outstanding one with Pop!_OS 21.10 beta on my 9700K/RX580 rig.*  Looks in Settings>About like I'm still using X11 (haven't researched how/why/whether to switch to Wayland manually).

`libpop-theme-switcher:amd64 (0.1.1~1634585152~21.10~426a5e4, 0.1.1~1636044688~21.10~abd8796), pop-cosmic:amd64 (0.1.0~1635889473~21.10~fbcaa2c, 0.1.0~1636070375~21.10~7730f99), gnome-shell-extension-cosmic-dock:amd64 (70~ubuntu1pop0~1635889396~21.10~acb33c1, 70~ubuntu1pop0~1636405927~21.10~92ae103), pop-shell:amd64 (1.1.0~1635267414~21.10~1fddaa8, 1.1.0~1636390326~21.10~b3595b2)`

Since this issue's already closed, I'll hope others benefit from the update. Coming together nicely!

*(Still having totally separate boot issues with the latest kernel on separate T9900/GeForce 9400M/9600M GT system as in issue #273.)

**Comment by leviport** [comment] 2021-11-10 21:24
New applications picker should be released soon: https://github.com/pop-os/cosmic/pull/218

I'm going to close this since it pertains to the old applications view.

**Closed by leviport** 2021-11-10 21:24 UTC
