### ISSUE TITLE
Pop! Shop not showing any updates when there are some avaliable.

### ISSUE THREAD

**Issue by agonzalez777** [pop-os/beta#303] opened 2021-11-15 19:28 UTC
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Fresh Install
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop-Shop / io.elementary.appcenter -  3.4.2pop0-1634231591~21.10~ee0f962

**Issue/Bug Description:**

Pop Shop! on Fresh ISO_2 install of 21.10 shows no updates avaliable when command line "sudo apt update" and "sudo apt upgrade" shows avaliable upgrades (20 as of today).

**Steps to reproduce (if you know):**
Fresh Install
Connect to Wireless
Open up Pop Shop

**Expected behavior:**
Pop Shop would show avaliable updates.

**Other Notes:**

**Comment by jacobgkau** [comment] 2021-11-15 19:37
Thank you for trying the beta. I'm closing this as a duplicate of https://github.com/pop-os/beta/issues/269. I've seen the issue too, and it will need to be fixed before release.

**Closed by jacobgkau** 2021-11-15 19:38 UTC
