### ISSUE TITLE
Can't close the applications menu by toggling it from dock or panel.

### ISSUE THREAD

**Issue by Outlaw-Amir** [pop-os/beta#360] opened 2022-04-02 08:19 UTC
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

 
upgraded to 22.04 beta by fresh install.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Can not exit the applications menu unless I press escape button or open an application. 

**Steps to reproduce (if you know):**

open the applications menu  from dock or panel.

**Expected behavior:**

to be able to toggle the application menu from the dock or the panel Applications button,
or just close it by clicking anywhere on the desktop.

**Other Notes:**

![Screenshot from 2022-04-02 12-42-50](https://user-images.githubusercontent.com/98311090/161373789-a04ff8a4-686c-45aa-b361-5eb943db0565.png)

**Comment by filnstuff** [comment] 2022-04-03 11:12
the only way you can close it is by clicking esc

**Comment by filnstuff** [comment] 2022-04-03 11:13
i hope the devs see this

**Comment by senntore** [comment] 2022-04-03 11:25
This is duplicate of https://github.com/pop-os/cosmic/issues/324, they're already working on this

**Comment by leviport** [comment] 2022-04-04 15:26
Should be fixed by https://github.com/pop-os/shell/pull/1389

**Closed by leviport** 2022-04-04 15:26 UTC
