### ISSUE TITLE
Pi400: Pop-Shell window loses focus, becomes unresponsive.

### ISSUE THREAD

**Issue by derpmatt** [pop-os/beta#339] opened 2021-12-12 01:32 UTC
Fresh Install. Written with `rpi-imager`. Using 32GB micro SD. Upgraded to latest - with every start. 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
It particularly happens with terminal. Both GNOME Terminal and xfce4-terminal.
`gnome-terminal:`
    `Installed: 3.38.1-1ubuntu1pop0~1633631287~21.10~ea92919`
`xfce4-terminal:`
    `Installed: 0.8.10-1`

**Issue/Bug Description:**
It appears like the focused window just loses focus, but doesn't apply it anywhere else.
I notice it in terminal, but I'm not totally sure if it is happening in other programs yet. Occasionally, a focused window will become unresponsive and will just stop accepting text while typing. When this happens, navigational KBS don't work. One fix is to use a mouse to left click the window which then allows typing and navigation to continue. Otherwise, restarting shell with alt + F2 `r` in x11 will allow the continuation of typing, but that messes up stacks and positioning. 
I've said Pop-Shell because that is what it happens to, but it could be COSMIC.

**Steps to reproduce (if you know):**
I haven't noticed any pattern or use that triggers it. 
It happens in both x11 and Wayland. It seems to happen early on after a boot. It can happen once or twice only per session. One occasion had up to four. 

**Expected behavior:**
Window doesn't lose focus and continues to accept text while typing.  Window responds to Pop-Shell KBS.

**Other Notes:**
I've attached a log captured from `journalctl -f` while it happened. Pop-Shell was in DEBUG mode. I've also included screenshot of my COSMIC and Pop-Shell settings.  No non-default GNOME extensions installed. I thought maybe DING was causing it so I toggled it off, but didn't change anything.
```
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab26d80910 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278f9a20 StButton.show-apps:first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fa170 Gjs_ui_iconGrid_BaseIcon.overview-icon:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab26d80910 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278f9a20 StButton.show-apps:first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fa170 Gjs_ui_iconGrid_BaseIcon.overview-icon:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fb900 StBoxLayout:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab26d80910 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278f9a20 StButton.show-apps:first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fa170 Gjs_ui_iconGrid_BaseIcon.overview-icon:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fb900 StBoxLayout:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fc2b0 StBin:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab26d80910 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278f9a20 StButton.show-apps:first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fa170 Gjs_ui_iconGrid_BaseIcon.overview-icon:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fb900 StBoxLayout:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fc2b0 StBin:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab27fda000 StIcon.show-apps-icon:insensitive] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab26d80910 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278f9a20 StButton.show-apps:first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fa170 Gjs_ui_iconGrid_BaseIcon.overview-icon:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab26d80910 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278f9a20 StButton.show-apps:first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fa170 Gjs_ui_iconGrid_BaseIcon.overview-icon:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fb900 StBoxLayout:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab26d80910 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278f9a20 StButton.show-apps:first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fa170 Gjs_ui_iconGrid_BaseIcon.overview-icon:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fb900 StBoxLayout:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fc2b0 StBin:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab26d80910 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278f9a20 StButton.show-apps:first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fa170 Gjs_ui_iconGrid_BaseIcon.overview-icon:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fb900 StBoxLayout:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab278fc2b0 StBin:insensitive first-child last-child] which is not in the stage.
Dec 12 09:58:39 pop-pi gnome-shell[1484]: st_widget_get_theme_node called on the widget [0xaaab27fda000 StIcon.show-apps-icon:insensitive] which is not in the stage.
```

![Screenshot from 2021-12-12 10-06-23](https://user-images.githubusercontent.com/49352270/145696956-cf27a252-a090-4824-bf8c-5483abe3ceb3.png)
![Screenshot from 2021-12-12 10-07-24](https://user-images.githubusercontent.com/49352270/145697126-22694bad-509f-4299-8cc4-aac06fd79c6a.png)
![Screenshot from 2021-12-12 10-08-24](https://user-images.githubusercontent.com/49352270/145697127-710007cb-afaa-47b6-aea0-ed80b446a196.png)
![Screenshot from 2021-12-12 10-09-05](https://user-images.githubusercontent.com/49352270/145697130-aca197c6-3e92-43cc-8e6f-6ac0e455c794.png)

**Comment by jacobgkau** [comment] 2021-12-13 16:12
This sounds like a duplicate of https://github.com/pop-os/beta/issues/333 and it should have been fixed by https://github.com/pop-os/cosmic/pull/259. Can you please confirm the version of COSMIC you're running with `apt policy pop-cosmic`?

**Comment by derpmatt** [comment] 2021-12-14 07:36
```
pop-cosmic:
  Installed: 0.1.0~1639168473~21.10~914a05e
  Candidate: 0.1.0~1639168473~21.10~914a05e
  Version table:
 *** 0.1.0~1639168473~21.10~914a05e 1001
       1001 http:/apt.pop-os.org/release impish/main arm64 Packages
        100 /var/lib/dpkg/status
```
Issue #333 certainly sounds similar.

**Comment by derpmatt** [comment] 2021-12-16 09:20
This issue seems to have been resolved with the upgrade to official release. However, I've now noticed another similar or associated issue that occurs on X11. New windows generated do not automatically get focus. You have to navigate to the new window. It's not happening on Wayland. 
 ```
Dec 16 18:54:25 pop-pi gnome-shell[1491]: Can't update stage views actor MetaWindowGroup is on because it needs an allocation.
Dec 16 18:54:25 pop-pi gnome-shell[1491]: Can't update stage views actor MetaWindowActorX11 is on because it needs an allocation.
Dec 16 18:54:25 pop-pi gnome-shell[1491]: Can't update stage views actor MetaSurfaceActorX11 is on because it needs an allocation.
Dec 16 18:54:41 pop-pi gnome-shell[1491]: Can't update stage views actor MetaWindowGroup is on because it needs an allocation.
Dec 16 18:54:41 pop-pi gnome-shell[1491]: Can't update stage views actor MetaWindowActorX11 is on because it needs an allocation.
Dec 16 18:54:41 pop-pi gnome-shell[1491]: Can't update stage views actor MetaSurfaceActorX11 is on because it needs an allocation.
Dec 16 18:54:48 pop-pi systemd[1279]: Started Application launched by gsd-media-keys.
Dec 16 18:54:48 pop-pi systemd[1279]: Started VTE child process 21139 launched by xfce4-terminal process 18011.
Dec 16 18:54:48 pop-pi systemd[1279]: app-gnome-x\x2dterminal\x2demulator-21134.scope: Deactivated successfully.
Dec 16 18:54:48 pop-pi gnome-shell[1491]: Could not create transient scope for PID 21148: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 21148 does not exist.
Dec 16 18:54:48 pop-pi gnome-shell[1491]: pop-shell: [DEBUG] attaching to window 3,5
```

**Closed** 2022-04-08 10:21 UTC
