### ISSUE TITLE
System Sound setting not being preserved.

### ISSUE THREAD

**Issue by zaphod80013** [pop-os/beta#271] opened 2021-11-02 00:29 UTC
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

Fresh install from 21.10 beta 1 intel
ran sudo apt update/upgrade immediately after install (approx 20:00 MDT 10/31) 
configured laptop via Ansible script (this does not include sound settings other than enabling over amplification)
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Settings --> Sound

**Issue/Bug Description:**

The system sound setting is not retained after closing settings, either sound level or on/off toggle.

**Steps to reproduce (if you know):**

1: open settings
2: navigate to sound settings
3: Adjust system sound level to around 35% (was on zero)
4: Close settings
5: Reopen setting
6: system sound level reset to zero

I see the same behavior with the speaker icon next to the system sound slider, I have a QTPulseAudio setting below system sound, moving that also resets system sound but the QT entry behaves as expected.

Behavior is consistent with the value of the system sound controls not being saved and the screen being refreshed from current settings.

**Expected behavior:**

Setting is preserved 

**Other Notes:**

I've executed many pop-upgrades (from 21.04) and more recently fresh installs from ISO while developing/testing my Ansible script to configure my laptop. I do NOT recall seeing this behavior before running update/upgrade on a fresh install for the first time yesterday. My hardware is a Galp5 Intel graphics.

**Comment by jacobgkau** [comment] 2021-11-02 20:47
Thank you for trying the beta. I'm not seeing this on a lab Intel galp5; I did see `System Sounds` set itself to 0% one time (which I don't think is entirely new), but I'm able to turn it back up, close/re-open Settings, reboot, and have the setting stick.

> I have a QTPulseAudio setting below system sound, moving that also resets system sound but the QT entry behaves as expected.

I'm having some trouble finding detailed information about QtPulseAudio, although I've found a few references to apps that use it. Do you know which app is adding that item to the sound settings? Are you using any ham radio apps? (If your Ansible script helps you recreate this and you're willing to share it, I could try running that, too.)

**Comment by zaphod80013** [comment] 2021-11-03 23:38
I'm not using ham radio as such (although I used to hold a G1 license in the UK before moving to Denver) but I am installing SDR apps which amounts to the same thing. I use a veracrypt vault to store configuration etc and the Ansible wouldn't run as is without it, Cant do it tonight but after work tomorrow I'll clone my repo, remove the vault key and either comment out the steps that wont work or create a dummy file system to replace the vault. and upload it to a public repo on github and post the link here.

**Comment by zaphod80013** [comment] 2021-11-04 01:00
Turned out I needed some info from the wife thingie to complete open enrollment and she's working late so I was able to hack my Ansible code into a new repo with sensitive data removed. it's here.

https://github.com/zaphod80013/temp.git

**Comment by zaphod80013** [comment] 2021-11-07 02:19
Reran the install using the beta 2 image and was unable to reproduce this error.

**Comment by zaphod80013** [comment] 2021-11-29 19:03
Ran a fresh "clean install" from beta 2 at the weekend and the problem re-appeared, Immediately re-ran a second 'clean install' and the issue did not reproduce. Again this was on my Galp5. Is there any specific information I should gather if I can repo the issue again?

**Comment by zaphod80013** [comment] 2021-12-07 05:02
Following on from above, problem reappeared after apt upgrade, was able to fix it by resetting sound in pavucontrol.

**Comment by n3m0-22** [comment] 2022-04-22 15:02
I've tested for this on 3 machines and can't reproduce the issues. If you are still seeing this we can always reopen, till then I'm closing the issue.

**Closed by n3m0-22** 2022-04-22 15:02 UTC
