### ISSUE TITLE
Pop Shell Applications menu can't be closed with mouse

### ISSUE THREAD

**Issue by Chinchzilla** [pop-os/beta#353] opened 2022-03-31 17:37 UTC
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

 
Upgrade
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

chinchzilla@chinchzilla-desktop:~$ apt policy pop-shell
pop-shell:
  Installed: 1.1.0~1648244449~22.04~a317816
  Candidate: 1.1.0~1648244449~22.04~a317816
  Version table:
 *** 1.1.0~1648244449~22.04~a317816 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

Pop Applications can't be exited with mouse (e.g. click away), clicking on "Applications" again, just with Escape button on keyboard 

**Steps to reproduce (if you know):**

Launch into desktop, click on applications either on Dock or Panel then try to exit it with click away or clicking again on applications

**Expected behavior:**

the window disappears

**Other Notes:**

**Comment by Chinchzilla** [comment] 2022-03-31 17:47
The animation on "Type to search" is also broken

**Comment by mmstick** [comment] 2022-03-31 17:49
Duplicate of https://github.com/pop-os/cosmic/issues/324

**Closed by mmstick** 2022-03-31 17:49 UTC
