### ISSUE TITLE
No Flatpak applications listed in Pop!_Shop

### ISSUE THREAD

**Issue by ghisvail** [pop-os/beta#10] opened 2020-04-09 07:53 UTC
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

Upgrade from 19.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
pop-shop:
  Installé : 3.1.1pop0~1585158386~20.04~cafc28e
  Candidat : 3.1.1pop0~1585158386~20.04~cafc28e
```

**Issue/Bug Description:**

No Flatpak applications are not listed in Pop!_Shop despite `Flathub` being correctly registered in repoman.

**Steps to reproduce (if you know):**

I had `flatpak` and the `Flathub` repo installed manually on Pop!_OS 19.10 using the following [instructions](https://flatpak.org/setup/Pop!_OS/).

After the upgrade, I wiped my flatpak install with `flatpak uninstall --all --delete-data --asumeyes` and tried to reinstall the Flatpak apps using Pop!_Shop.

Unfortunately, none of them are listed. I tried Slack, Steam or VSCode, only the DEB versions are available for install. I can still install them from the command-line via regular `flatpak install flathub $APP_ID`.

**Expected behavior:**

Flatpak-only applications should be listed in Pop!_Shop (for instance VSCode **OSS**). Other applications available both as DEB and Flatpak should list `Flathub` as a source in the choice menu alongside the install button.

**Comment by ghisvail** [comment] 2020-04-14 06:48
Shall I report this issue directly to https://github.com/pop-os/shop ?

**Comment by Kartonrealista** [comment] 2020-04-14 06:51
I looked at the Pop!_Shop and some of the apps that you said were unavailable could be downloaded, there are also flatpak versions of some, but not all dual-version apps.

**Comment by WatchMkr** [comment] 2020-04-17 04:09
I'm unable to reproduce this on upgrades and fresh installs. When you open Pop Shop, click the cog at the top right. Click the Flatpak tab and make sure the repo is there.

![flatpak-repo](https://user-images.githubusercontent.com/3430283/79531208-de05e280-802e-11ea-9390-ab48f79916c7.png)

**Comment by ghisvail** [comment] 2020-04-17 06:53
> When you open Pop Shop, click the cog at the top right. Click the Flatpak tab and make sure the repo is there.

This is what I got:

![Capture d’écran de 2020-04-17 08-34-45](https://user-images.githubusercontent.com/1964655/79540135-e76f6900-8087-11ea-89b5-0b8946ea7781.png)

Now I suspect you did not exactly follow the reproducibility steps I highlighted, since your Flathub **Type** is different than mine (System vs User). I am glad to hear the issue does not manifest itself when installing fresh from the new 20.04 beta :+1: .

Nevertheless, the point of this issue is to show that Pop!_Shop *can* end up in a state where flatpak support is broken despite a healthy initial flatpak setup before upgrade to 20.04. I don't know whether it's a software, config or cache issue, the point remains that it can.

**Comment by isantop** [comment] 2020-04-17 17:25
The issue here appears to be that the flatpakrepo was added in System mode (which is the default for the flatpak CLI). Pop Shop currently only supports remotes and Apps installed in user mode, which allows each user to have their own apps installed, and doesn't require authentication to install, update, or remove apps. 

System- and User-mode Flatpak repositories are treated differently by the flatpak system. The only way to correct this is to remove existing Flatpak Apps and remove the remote, then re-add the remote using the Pop Shop settings (or via the command line using the `--user` flag) to set them up in User mode.

**Comment by ghisvail** [comment] 2020-04-18 06:15
You were correct. I ran `flatpak uninstall --all`, followed by `flatpak remote-delete flathub` and registered the Flathub repository via Repoman. The Flathub remote is now listed as `User` instead of `System` and flatpak apps are correctly listed and searchable. Thanks @isantop 

If not done already, it might be worth to add a comment to the release note regarding the migration of existing flatpak setup to 20.04. I suppose other flatpak users upgrading from 18.04 or 19.10 may face the same issue later.

**Comment by isantop** [comment] 2020-04-20 15:10
I think we want to have a "Convert" button which will automatically add the remote in user-mode, then reinstall any applications from the System remote in the new user-mode one.

**Comment by tobaccoblonde** [comment] 2020-09-08 06:51
i've encountered this feature in a different way. i have system flatpaks available to all users. there's a fun discrepancy in this approach, each user can install multiple versions of the same flatpak, which is undesirable. however, from the user's perspective in the pop shop it looks like that application isn't installed, so everything looks legitimate.

i was wondering if there could be a user experience that could include system flatpaks in the pop shop in a meaningful way?

**Comment by mmstick** [comment] 2020-09-08 07:30
@tobaccoblonde elementary appcenter doesn't support it, but I believe they're working on it. It's just considered ideal for flatpaks to be installed by users instead of system-wide. No root required that way. Different users have different software needs.

**Comment by tobaccoblonde** [comment] 2020-09-08 09:01
@mmstick that's cool they might be working on it, i hope something like it happens. i agree that system wide flatpak's might not be ideal. but it has less unique quirks per application than installing everything in /usr/share/... the last piece of my little project is easy GUI updates. sudo flatpak update will have to suffice.

maybe there is another way to do this, so that a small suite of applications are recognised system wide for all users, and there is no significant challenge to update them.

**Comment by cassidyjames** [comment] 2020-09-08 23:03
Support for system-wide Flatpaks in AppCenter was merged a couple of weeks ago and is due for the 3.5 release which is being reviewed.

**Comment by bflanagin** [comment] 2021-06-09 16:46
Thank you for your report! With 21.04 fast approaching we're closing older issues from previous betas. If you would like to try the latest beta and report issue you find there check out the latest install instructions [here](https://github.com/pop-os/beta).

**Closed by bflanagin** 2021-06-09 16:46 UTC
