### ISSUE TITLE
Running apt dist-upgrade trashes the entire system and makes it unbootable

### ISSUE THREAD

**Issue by KitsuneAlex** [pop-os/beta#373] opened 2022-04-05 12:55 UTC
**How did you upgrade to 22.04? (Fresh install / Upgrade)**
I did a fresh install.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
I honestly don't know but i have a strong feeling this is related to #372 

**Issue/Bug Description:**
Using apt dist-upgrade finished normally, but when rebooting the system, it's stuck at a blinking cursor prompt.

**Steps to reproduce (if you know):**
- Fresh-install 22.04 from the NVIDIA ISO
- Run **apt dist-upgrade**

**Expected behavior:**
I don't expect any package to install all the time, but i also expect the command to not wreck my entire installation.

**Other Notes:**

**Comment by mmstick** [comment] 2022-04-05 14:08
Duplicate of #372

**Closed by mmstick** 2022-04-05 14:08 UTC

**Comment by KitsuneAlex** [comment] 2022-04-05 14:23
Sorry, thanks for pointing that out! ^^
