### ISSUE TITLE
Windows overlap workspace area (main monitor)

### ISSUE THREAD

**Issue by leonamduarte** [pop-os/beta#223] opened 2021-10-13 23:40 UTC
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

Fresh Install

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Everytime i hit super+d to see my main monitor's workspace, any windows I have open overlaps the workspace area. I looks like to only happen on my main monitor.

**Steps to reproduce (if you know):**

Just hit super+d with any window open

**Expected behavior:**

**Other Notes:**
![Captura de Tela-20211013203052-1598x899](https://user-images.githubusercontent.com/92490775/137226886-2893abcf-1049-45aa-893b-b9ccae3ebf76.png)

![gnome-shell-screenshot-XR04A1](https://user-images.githubusercontent.com/92490775/137227257-623668e9-b7ab-4356-8f23-27a3f1c84e84.png)

**Comment by dipanshparmar** [comment] 2021-10-14 06:23
Hey @wangsora how did you get that horizontal workspace view. For me it is vertical as you shown in the first image. How can I get this horizontal view?

**Comment by leviport** [comment] 2021-10-14 14:10
Duplicate of https://github.com/pop-os/gnome-shell-extension-vertical-overview/issues/4

**Closed as completed by leviport** 2021-10-14 14:10 UTC
